# Generated by Django 4.2.24 on 2025-09-25 12:46

from django.db import migrations, models
import uuid
# accounts/migrations/0002_...py

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        # 1. Altera o tipo da coluna id para UUIDField
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]