# Generated by Django 4.2.24 on 2025-09-25 17:51
# accounts/migrations/0004_....py
from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
    ]

    operations = [
        # 1. Adiciona uma nova coluna de UUID temporária
        migrations.AddField(
            model_name='user',
            name='uuid_id',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),

        # 2. Executa um comando SQL para copiar dados do 'id' para 'uuid_id'
        migrations.RunSQL(
            "UPDATE accounts_user SET uuid_id = gen_random_uuid();"
        ),

        # 3. Remove a coluna 'id' original
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),

        # 4. Renomeia a nova coluna 'uuid_id' para 'id'
        migrations.RenameField(
            model_name='user',
            old_name='uuid_id',
            new_name='id',
        ),

        # 5. Define a nova coluna 'id' como chave primária
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]